### ISSUE TITLE
OpenCVCameraコンポーネントの動作が遅い

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/ImageProcessing#1]
**Describe the bug**
OpenCVCameraコンポーネントの動作が遅くなる場合がある。

**To Reproduce**
1. OpenCVCameraCompを実行
2. RTCをアクティベート

**Reproducibility**
環境によっては100％発生

**Expected behavior**

**Screenshots or Logs**

**Environment**
 - OS: Ubuntu 16.04(MacOS Pallarels上で起動)
 - OpenRTM-aist Version 2.0

**Additional context**

**Comment by n-kawauchi** [comment]
Ubuntu 16.04(MacOS Pallarels上で起動)環境で確認しました。CameraViewerとの接続動作では問題ありませんでした。
修正前のOpenCVCameraはフレームレート出力間に「HIGHGUI ERROR: V4L: Unable to set camera FPS
」のメッセージが出ていましたが、修正後はこれが一切出力されなくなったので改善されました。
